# Generated by Django 3.0.7 on 2020-06-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('t_min', models.FloatField()),
                ('t_max', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PressureClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Group')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Material')),
                ('pressure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.PressureClass')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Standard')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pressure_m29', models.FloatField()),
                ('pressure_38', models.FloatField()),
                ('pressure_50', models.FloatField()),
                ('pressure_100', models.FloatField()),
                ('pressure_150', models.FloatField()),
                ('pressure_200', models.FloatField()),
                ('pressure_250', models.FloatField()),
                ('pressure_300', models.FloatField()),
                ('pressure_325', models.FloatField()),
                ('pressure_350', models.FloatField()),
                ('pressure_375', models.FloatField()),
                ('pressure_400', models.FloatField()),
                ('pressure_425', models.FloatField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Group')),
                ('pressure_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.PressureClass')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='output_pressure.Standard'),
        ),
    ]
